
import javax.swing.JOptionPane;
/**
 *
 * @author aluno
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_img = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_matricula = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        btn_gravar = new javax.swing.JButton();
        lbl_ver = new javax.swing.JLabel();
        slider_matricula = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(51, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setForeground(new java.awt.Color(51, 0, 102));
        setMinimumSize(new java.awt.Dimension(500, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_img.setForeground(new java.awt.Color(255, 51, 51));
        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/img_starcio.png"))); // NOI18N
        lbl_img.setMaximumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(lbl_img);
        lbl_img.setBounds(390, 30, 68, 76);

        lbl_titulo.setBackground(new java.awt.Color(120, 0, 220));
        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(100, 0, 200));
        lbl_titulo.setText("Cadastro de Cliente");
        getContentPane().add(lbl_titulo);
        lbl_titulo.setBounds(140, 20, 230, 30);

        lbl_matricula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_matricula.setForeground(new java.awt.Color(255, 0, 0));
        lbl_matricula.setText("Matricula");
        getContentPane().add(lbl_matricula);
        lbl_matricula.setBounds(60, 90, 70, 20);

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(255, 0, 0));
        lbl_nome.setText("Nome");
        getContentPane().add(lbl_nome);
        lbl_nome.setBounds(60, 160, 70, 20);
        getContentPane().add(txt_matricula);
        txt_matricula.setBounds(60, 110, 110, 30);
        getContentPane().add(txt_nome);
        txt_nome.setBounds(60, 180, 330, 30);

        btn_gravar.setForeground(new java.awt.Color(102, 51, 255));
        btn_gravar.setText("Gravar");
        btn_gravar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gravar);
        btn_gravar.setBounds(210, 220, 72, 23);

        lbl_ver.setText("v.01");
        getContentPane().add(lbl_ver);
        lbl_ver.setBounds(10, 260, 37, 16);

        slider_matricula.setMaximum(999999999);
        slider_matricula.setOrientation(javax.swing.JSlider.VERTICAL);
        slider_matricula.setSnapToTicks(true);
        slider_matricula.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(slider_matricula);
        slider_matricula.setBounds(30, 100, 20, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        JOptionPane.showMessageDialog(null, "parabens voce criou a entrada de dados(não de verdade)");      // TODO add your handling code here:
    }//GEN-LAST:event_btn_gravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gravar;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_ver;
    private javax.swing.JSlider slider_matricula;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
